config/routes.rb
AlbumApp::Application.routes.draw do
  
  get "home/index"
    
  resources :albums do 
    resources :photos
     
  end

  devise_for :users ,:path_names => {:sign_up => 'register',:sign_in => 'login'}

  root :to => "home#index"

end

app/models/album.rb
class Album < ActiveRecord::Base
   cattr_reader :per_page
   @@per_page = 6

  has_many :photos,:dependent => :destroy
  belongs_to :user
  
  accepts_nested_attributes_for :photos
  
  validates :album_name ,:presence => true
  
  
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  
  cattr_reader :per_page

  belongs_to :album
  acts_as_taggable_on :tags
 # belongs_to :user
  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  
  validates :title,:presence => true
  validates_attachment_presence :image
  validates_attachment_size :image, :less_than => 5.megabytes
  
  def self.destroy_pics(album,photos)
    @del= Photo.find(photos,:conditions => {"album_id" => album} ).each(&:destroy)
  end
  
end

app/models/user.rb
class User < ActiveRecord::Base
  
  has_many :albums,:dependent => :destroy
  #has_many :photos,:dependent => :destroy
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  respond_to :html,:xml
  before_filter :load, :only => [:show,:edit,:update,:destroy,:tag_cloud]
  before_filter :authenticate_user!
  
    
  def index
    
    
    @albums = Album.paginate(:all,:page => params[:page])
    
    respond_with(@albums)
     
  end

  
  def show
    @photos = @album.photos.paginate(:all,:page => params[:page],:per_page => 6)
    respond_with(@album)
      
  end

  
  def new
    @album = Album.new
    respond_with(@album)
  end

  
  def edit
   
  end

  
  def create
    @album = Album.create(params[:album])
   
    if @album.save
      flash[:notice] = "Album Created Successfully"
    end
    respond_with(@album)
  end

  
  def update
    unless params[:photo_ids].empty?
       Photo.destroy_pics(params[:id], params[:photo_ids])
    end   
    respond_to do |format|
      if @album.update_attributes(params[:album])
        format.html { redirect_to(@album, :notice => 'Album was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @album.errors, :status => :unprocessable_entity }
      end
    end
  end

  
  def destroy
    @album.destroy
    respond_to do |format|
      format.html { redirect_to(albums_url) }
      format.xml  { head :ok }
    end
  end
  
 
  
  private
  
  def load
    
    @album = Album.find(params[:id])
  end
  
  
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
    @albums = Album.all
    @tags = []
    @albums.each do |a|
      a.photos.each do |p|
        @tags << p.tag_list
      end
    end
    
  end
  
  
  
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  
  def index
    
    
   
  end
      
  end
  
  def show
   
    
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  include ActsAsTaggableOn::TagsHelper
  

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/albums/_add.html.erb
 <% form_for @album,:html => { :multipart => true } do |f| %>
    
      <%= f.fields_for :photos,[@album.photos.build] do |p| %>
        <%= render :partial => 'photo',:locals => {:form => p } %>
      <% end %>
      <br/><br/>  
     <%= f.submit %>
    
 <% end %>

app/views/albums/_form.html.erb
<%= form_for(@album) do |f| %>
  <% if @album.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@album.errors.count, "error") %> prohibited this album from being saved:</h2>

      <ul>
      <% @album.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <label>Album Name :</label><%= f.text_field :album_name %>
  <br/><br/>
  <label>Description : <label><%= f.text_area :album_description,:rows => '6',:cols => '80' %>
  <br/><br/>
  <%= f.hidden_field :user_id, :value => current_user.id %>

  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/albums/_photo.html.erb
  <label>Image Path : </label>
  <%= form.file_field :image %><br/><br/>
  
  <label>Image Caption : </label>
  <%= form.text_field :title %><br/><br/>
  
  <label>Description : </label><br/>
  <%= form.text_area :description,:cols => "80",:rows => '6' %><br/><br/>
  
  <label>Tags : <label><br/>
  <%= form.text_field :tag_list %>
  
  <%= link_to "Cancel","#",:onclick => "remove_add_pic();" %>

app/views/albums/edit.html.erb
<% content_for :content do %>

  <h2>Editing <%= @album.album_name %></h2>
  <br/>
  <hr/>
  <br/><br/>
  <span style="float :right;"><%= link_to 'Show', @album %> &nbsp; &nbsp;<%= link_to 'Back', albums_path %></span>
  <br/><br/>
  <%= link_to "Click to Add Photos","#",:onclick => "add_pic();" %>
  <br/><br/>
  <%#= render 'form', :object => @album %>
  <br/><br/>
  <hr/><br/><br/>
  <%= form_for(@album) do |f| %>
  
    <% if @album.photos.empty? %>
      There are no Photos present.
    <% else %> 
      <% @album.photos.each do | photo | %>
         <%= image_tag(photo.image.url(:thumb), :alt => '') %>
         <%= check_box_tag "photo_ids[]",photo.id %>
      <% end %>
    <% end %>
    <br/><br/>
    
     <%= f.submit "Remove Selected Items" %>
   <% end %>
 
  

  <div id="add_ph" style="display:none;z-index:1000;border: 1px solid;padding:56px;top:200px;width: 600px;height:auto;position: absolute;background: black;" %>
      <%= render "add",:object => @album %>
  </div>

  
<% end%>

app/views/albums/index.html.erb
<% content_for :content do %>
  <%= will_paginate @albums , :style => "float: right;"%>

  <h2>Album List</h2>
  <br/>
  <hr/>
  <br/><br/>
  <span style="float :right;"><%= link_to 'Add Album', new_album_path %></span>
  <br/><br/>
  
  <br/><br/>
    <% if !current_user.albums == nil && current_user.albums.empty? %>
        You Do Not Have Any Albums Yet.
      <%= link_to "Click To Create Album",new_album_path %>
    <% else %>
     
    <ul style="list-style: none;">
      <% @albums.each do |album| %>
        <li style="height: 300px; width: 300px;float: left; padding: 20px;">
           <div style="float:left;"><b><%= album.album_name %></b></div>
            <div style="float:right;"><%= link_to 'Show', album %> | <%= link_to 'Edit', edit_album_path(album) %> |
              <%= link_to 'Destroy', album, :confirm => 'Are you sure?', :method => :delete %> </div>
       
          <br/><br/>
          <%= image_tag(album.photos.first.image.url(:medium)) unless album.photos.empty? %>
          <br/><br/>
          <div>
            <%= album.album_description %><br/><br/>
          </div>
        </li>
    <% end %>
    <% end %>  
        <br />
  
  <% end %>

app/views/albums/new.html.erb
<% content_for :content do %>
  <h2>New album<h2>
  <br/>
  <hr/>
  <br/><br/>
  <span style="float :right;"><%= link_to 'Back', albums_path %></span>
  <br/><br/>
  <%= render 'form', :object => @album %>
  
 <% end %>

app/views/albums/show.html.erb
<% content_for :content do %>
  <%= will_paginate @photos ,:style => "float: right;" %>

  <h2><%= @album.album_name %></h2><br/>
  <hr/><br/><br/>
   
  <span style="float :right;"><%= link_to 'Edit', edit_album_path(@album) %>&nbsp;&nbsp;
  <%= link_to 'Back', albums_path %></span>&nbsp;&nbsp; <%= link_to "Click to Add Photos","#",:onclick => "add_pic();" %>
  <br/><br/>
  
  
  <% if @album.photos.empty? %>
    There are no Photos present.
  <% else %>
   <div id="gallery">
       <ul style="list-style:none;">
          <% @photos.each do | photo | %>
              <li style="float: left;padding: 20px;"><%= link_to image_tag(photo.image.url(:medium)),photo.image.url %></li>
           <% end %>
       </ul>
     </div>

   
  <% end %>



  <div id="add_ph" style="display:none;z-index:1000;border: 1px solid;padding:56px;top:200px;width: 600px;height:auto;position: absolute;background: black;" %>
      <%= render "add",:object => @album %>
  </div>

  
  
<% end %>

app/views/home/_landing_page.html.erb
<span style="float: left;"><h2> Welcome back,<%= current_user.email %></h2></span><span style="float: right"> Want to <%= link_to "Create a New Album" , new_album_path %></span>

<br/><br/>
<hr/>
<br/><br/>
<% if current_user.albums.empty? %>

  <i>You Have 0 Albums.</i>
  <br/><br/>
  
  <%= link_to "Create a New Album", new_album_path %>
  
<% else %>

  <i>You Have <%= current_user.albums.count %> Albums.</i>
  <br/><br/>
  Click on Albums to View/Edit them.
  <br/><br/>
  <br/><br/>
  
<% end %>
<hr/>
<br/><br/>

<% if @tags.empty? %>
    No Tags
<% else %>
    Tags:
    <% tag_cloud(@tags, %w(css1 css2 css3 css4)) do |tag, css_class| %>
      <%= link_to tag,'#', :class => css_class %>
    <% end %>
<% end %> 
  <br/><br/>
  

app/views/home/index.html.erb
<% content_for :content do %>
      
  <div>
     <% if !user_signed_in? %>
         <h2>WELCOME TO THE ALBUM APPLICATION</h2> 
        <br/><br/>
        <b> Click Here to <%= link_to "Login" , new_user_session_path %> </b>
     <% else %>
        
        <%=  render "landing_page" %>  
     <% end %>
  </div>
    
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

       <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

       <title>Webalbum</title>
       <%= stylesheet_link_tag 'styles','lightbox'%>
       <%= javascript_include_tag 'jquery.min','rails','application','lightbox' %>

       <%= csrf_meta_tag %>

  </head>

  <body>
      <section id="page">
           <header> 
                <br/><br/>
                <hgroup>
                    <h1>Album</h1>
                </hgroup>
                <div style="float:right;">
                   <% if user_signed_in? %>
                      Welcome ,<b><%= current_user.email %></b> |
                                <%= link_to 'Sign Out',destroy_user_session_path %> 
                   <% end %>
                </div>
            </header>
            <br/><br/>
              <nav class="clear" style="float :left;"> 
                    <% if user_signed_in? %>    
                      <ul>
                         <li style="padding-right: 10px;"><%= link_to 'Home', root_url %></li>
                         <li style="padding-right: 10px;"><%= link_to 'Albums',albums_path %></li>
                      </ul>
                    <% end %>
                </nav>    

        <section id="articles">
          
            <div id="container">
              <% if flash[:notice] %>
               <div class="flash">
                <div class="notice"><%= flash[:notice] %></div>
               </div>
              <% end %>
              <br/><br/>
               <%= yield :content %>
            </div>
        </section>

         </section>




  </body>
</html>